a1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^', include('wordbank.urls')),
     url(r'^admin/', admin.site.urls),
     
]

wordbank/urls.py
from django.conf.urls import url

from . import views

app_name = 'wordbank'
urlpatterns = [
    url(r'^$', views.Home_page, name='home_page'),
    url(r'^(?P<word_text>[a-z]+)/detail/$', views.DetailView, name='detail'),
    url(r'^AllView/$', views.AllView, name='allview'),
    url(r'^addform/$', views.AddWordForm, name='addword'),
    url(r'^saveword/$', views.SaveWord, name='saveword'),
    url(r'^search/$', views.SearchWord, name='searchword'),
    url(r'^upload/$', views.Upload, name='upload'),
    url(r'^loadcsv/$', views.Loadcsvfile, name='loadcsv'),
    url(r'^backup/$', views.Backup, name='backup'),
    url(r'^backupxml/$', views.BackupXML, name='backupxml'),
    url(r'^uploadxml/$', views.UploadXML, name='uploadxml'),
    url(r'^loadxml/$', views.Loadxmlfile, name='loadxml'),
]

wordbank/models.py
from django.db import models
from datetime import datetime

class Word(models.Model):
    word_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=datetime.now, blank=True)
    word_count = models.IntegerField(default = 0)
    word_latest = models.CharField(max_length=200)
    def __str__(self):
        return self.word_text
    
class Detail(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    type_text= models.CharField(max_length=200)
    mean_text= models.CharField(max_length=200)
    sentence_text= models.CharField(max_length=200)
    
   
        
        
    

wordbank/views.py
import csv
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.core.files.storage import default_storage
from .models import Word, Detail
import xml.etree.cElementTree as ET
import time
import datetime
import os
from xml.etree import ElementTree
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import SubElement

def Home_page(request):
    top_5 = Word.objects.order_by('-pub_date')[:5]
    top_list_search = Word.objects.order_by('-word_count')[:5]
    top_latest_search = Word.objects.order_by('-word_latest')[:5]
    
    return render(request, 'wordbank/home_page.html',{'top_5':top_5, 'top_list_search':top_list_search, 'top_latest_search':top_latest_search})

def AllView(request):
    all_word_list = Word.objects.order_by('word_text')
    context = {'all_word_list':all_word_list}
    return render(request,'wordbank/allview.html',context)

def DetailView(request, word_text):
    word = get_object_or_404(Word, word_text=word_text) 
    context = {'word':word}
    return render(request,'wordbank/detail.html',context)



def AddWordForm(request):
    return render(request,'wordbank/addword.html')

def SaveWord(request):
    error = None
    if request.method == 'POST':
        add_word = request.POST['add_word']
        add_type = request.POST['add_type']
        add_mean = request.POST['add_mean']
        add_sentence = request.POST['add_sentence']
        add_datetime = timezone.now()
        if add_word == "" or add_type == "" or add_mean == "" or add_sentence == "" :
            error = 'add all box please'
            return render(request,'wordbank/addword.html',{'error':error})
        if Word.objects.filter(word_text=add_word):
            same_word = Word.objects.get(word_text=add_word)
            same_word.detail_set.create(type_text = add_type, mean_text =add_mean,sentence_text=add_sentence  )
                 
        
        else:
            new_word = Word(
            word_text = add_word,
            pub_date  = add_datetime
            )
            new_word.save()
            new_word.detail_set.create(type_text = add_type, mean_text =add_mean,sentence_text=add_sentence  )
            
                      
                
    return HttpResponseRedirect(reverse('wordbank:home_page'))

def SearchWord(request):
    top_list_search = Word.objects.order_by('-word_count')[:5]
    top_latest_search = Word.objects.order_by('-word_latest')[:5]
    if request.method == 'POST':
        search = str(request.POST['searchword'])
        if Word.objects.filter(word_text = None):
            return render(request,'wordbank/home_page.html')
        elif Word.objects.filter(word_text=search):
            word = Word.objects.get(word_text=search)
            word_search = get_object_or_404(Word,id = word.id)
            word_search.word_count += 1 
            word_search.word_latest = timezone.now()
            word_search.save()
     
            return render(request,'wordbank/searchword.html',{'word':word})
       
        
    
    return render(request,'wordbank/showsearch.html',{'search':search})
def ShowSearch(request):
    
    print(top_list_search)
    print(top_latest_search)
    return render(request,'wordbank/home_page.html',{'top_list_search':top_list_search, 'top_latest_search':top_latest_search })


    
    
    
def Upload(request):
    return render(request,'wordbank/upload.html')
def Loadcsvfile(request):
    dirPath = 'wordbank/loadcsv/'
    if request.FILES != {}:  # if have file uploaded
        csvFile = request.FILES['csvFile']
        saveFilePath = default_storage.save(dirPath,csvFile)
        os.rename(saveFilePath,'{}word.csv'.format(dirPath))
        all_word = Word.objects.all()
        for word in all_word:
            word.delete()  # delete all before read word in csv
        with open('wordbank/loadcsv/word.csv') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                if row['word'] != '':
                    word = Word(word_text=row['word'])
                    word.save()
                else:
                    word.detail_set.create(type_text=row['type'], mean_text=row['meaning'],sentence_text=row['sample_sentence'])
            
            return HttpResponseRedirect(reverse('wordbank:home_page'))
    else:
        return HttpResponseRedirect(reverse('wordbank:upload'))  # not read file if haven't file uploaded

def Backup(request):
    list_word = Word.objects.order_by('word_text')
    with open('wordbank/backup/backup.csv', 'w') as csvfile:
        fieldnames = ['word', 'date', 'type', 'mean',  'example']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for word in list_word:
            for detail in word.detail_set.all():
                writer.writerow({'word':word.word_text, 'date':word.pub_date, 'type': detail.type_text, 'mean': detail.mean_text,
				 'example': detail.sentence_text})
    return HttpResponseRedirect(reverse('wordbank:home_page'))



def BackupXML(request):
    all_word = Word.objects.all()
    root = ET.Element("wordbank")
    for each_word in all_word:
        word = ET.SubElement(root,"Word")
        word.set("word",each_word.word_text)
        for each_detail in each_word.detail_set.all():
            detail = ET.SubElement(word, "detail")
            ET.SubElement(detail, "type").text = each_detail.type_text
            ET.SubElement(detail, "mean").text = each_detail.mean_text
            ET.SubElement(detail, "sentence").text = each_detail.sentence_text

    tree = ET.ElementTree(root)
    tree.write('wordbank/backup/XML_.xml')
    return HttpResponseRedirect(reverse('wordbank:home_page'))

def UploadXML(request):
    return render(request,'wordbank/uploadxml.html')

def Loadxmlfile(request):
    if request.method == 'POST':
        all_word = Word.objects.all()
        document = ElementTree.parse('wordbank/backup/XML_.xml')
        for word in all_word:
            word.delete()
        for word_ in document.findall('Word'):
            if Word.objects.filter(word_text=word_.attrib['word']).count() == 0:
                new = Word(word_text=word_.attrib['word'])
                new.save()
        all_word = Word.objects.all()
        for save_word in document.findall('Word'):
            _word = save_word.attrib['word']
            for word__ in all_word:
                if word__.word_text == _word:
                    word__.detail_set.create(type_text=save_word.find('type').text,
                                             mean_text=save_word.find('mean').text,
                                             sentence_text=save_word.find('sentence').text)
    return HttpResponseRedirect(reverse('wordbank:home_page')) 

       
        
            
          
 


    

wordbank/templates/wordbank/addword.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
<title>wordbank</title>
</head>
<body>
<h2>Add New Word</h2>
<form action="{% url 'wordbank:saveword' %}" method="POST">
{% csrf_token %}
Word : </br>
<input type="text" name="add_word"><br/>
Type : </br>
<input type="text" name="add_type" ><br/>
Meanning : </br>
<input type="text" name="add_mean"  ><br/>
Sample Sentence : </br>
<input type="text" name="add_sentence"  ><br/>


<input type="submit" name= "submit" value="submit" />

</form>
{{error}}
<a href="{% url 'wordbank:home_page'  %}">back</a>
</body>
</html>

wordbank/templates/wordbank/allview.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
<title>WordBank</title>
<h1>AllWord</h1>
</head>
<body>
{% if all_word_list %}
    {% for word in all_word_list %}
<<<<<<< HEAD

       <h3><a href="{% url 'wordbank:detail' word.word_text %}">{{ word.word_text }}</a></h3>      
=======
        <h3><a href="{% url 'wordbank:detail' word.word_text %}">{{ word.word_text }}</a></h3>      
>>>>>>> c9ac8ad379997f4687577a67bc675b3f4ebf5299
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
<body>
</html>

wordbank/templates/wordbank/detail.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
        <title>Detail</title>
</head>
<meta
http-equiv=”Content-Type” content=”text/html;
charset=UTF-8″>
<body>
<h1>{{ word.word_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for detail in word.detail_set.all %}
    <p class="one">Type : {{ detail.type_text }}</p>
    <p class="one">Meanning : {{ detail.mean_text }}</p>
    <p class="one">Sample Sentence : {{ detail.sentence_text }}</p>
    <hr>    
    {% endfor %}
<a href="{% url 'wordbank:home_page'  %}">back</a>
</body>
</html>

wordbank/templates/wordbank/home_page.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
<title>WordBank</title>
<h1>WordBank</h1>
</head>
<ul>
<li><a class="active" href="{% url 'wordbank:allview' %}">All Word</a></li>
<li><a class="active" href="{% url 'wordbank:addword' %}">Add Word</a></li>
<li><a class="active" href="{% url 'wordbank:upload' %}">Upload CSV Word</a></li>
<li><a class="active" href="{% url 'wordbank:backup' %}">Backup With CSV</a></li>
<li><a class="active" href="{% url 'wordbank:backupxml' %}">Backup With XML</a></li>
<li><a class="active" href="{% url 'wordbank:uploadxml' %}">Upload With XML</a></li>
</ul>
<h2>Latest 5 Word</h2>
<body>
{% if top_5 %}
    
    {% for word in top_5 %}
       <p class= "one"><a href="{% url 'wordbank:detail' word.word_text %}">{{ word.word_text }}</a></p>      
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
<form action="{% url 'wordbank:searchword' %}" method="POST">
        {% csrf_token %}
            <tr><td><input type="text" name="searchword" size="20" style="height:35px" placeholder="  Search . . . ."/></td></tr>
            <tr><td align="center"><input type="submit" name="search" value="Search" style="width:100px; height:45px"/></td></tr>
        
    </form>
{{search}}

<h2>top search 5 :</h2>

{% for count in top_list_search %}
    
<b>{{count}}</b> ,{{count.word_count}}<br>

{% endfor %}
 
<h2>latest search 5 :</h2>
{% for latest in top_latest_search %}
    <b>{{latest}}</b>,{{latest.word_latest}}<br>

{% endfor %}
</body>
<html>

wordbank/templates/wordbank/searchword.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
        <title>Detail</title>
</head>
<meta
http-equiv=”Content-Type” content=”text/html;
charset=UTF-8″>
<body>

<h1>{{ word.word_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for detail in word.detail_set.all %}
    <p class="one">Type : {{ detail.type_text }}</p>
    <p class="one">Meanning : {{ detail.mean_text }}</p>
    <p class="one">Sample Sentence : {{ detail.sentence_text }}</p>
    <hr>    
    {% endfor %}


<a href="{% url 'wordbank:home_page'  %}">back</a>
</body>
</html>

wordbank/templates/wordbank/upload.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordbank/style.css' %}" />
<html>
<head>
<title>WordBank</title>
<h1>LoadCSV</h1>
</head>
<body>
<form action="{% url 'wordbank:loadcsv' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Select your file:
         <input type="file" name="csvFile" id="csvFile" ><br>
         <input type="submit" name="loadcsv" name ="submit"><br>
</form>
</body>
</html>